# 基础镜像
FROM redis
# author
MAINTAINER uuc

# 挂载目录
VOLUME /home/uuc/redis
# 创建目录
RUN mkdir -p /home/uuc/redis
# 指定路径
WORKDIR /home/uuc/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/uuc/redis/redis.conf
