apiVersion: v1
kind: Service
metadata:
  name: dev-cmdb-cmdb-config
  namespace: ${NAMESPACE}
spec:
  type: ExternalName
  externalName: cmdb-config.dev-cmdb.svc.cluster.local
  ports:
  - name: http
    port: 9211
    targetPort: 9211
