# spring配置
spring:
  # 环境迁移需根据实际情况改动，Redis配置
  redis:
    host: 10.128.40.206
    port: 6379
    password: Q1^dzq5H4H
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      # 环境迁移需根据实际情况改动，druid连接词用户密码配置
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        # 环境迁移需根据实际情况改动，一般不用调整
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        # 主库数据源
        # 环境迁移需根据实际情况改动，monitor_mon数据库配置
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.128.40.205:3306/monitor_mon?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Public-service#123
        # 从库数据源
        # 环境迁移需根据实际情况改动，monitor_rdb数据库配置
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.128.40.205:3306/monitor_rdb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Public-service#123
# seata配置
seata:
  # 默认关闭，如需启用spring.datasource.dynami.seata需要同时开启
  enabled: false
  # Seata 应用编号，默认为 ${spring.application.name}
  application-id: ${spring.application.name}
  # Seata 事务组编号，用于 TC 集群名
  tx-service-group: ${spring.application.name}-group
  # 关闭自动代理
  enable-auto-data-source-proxy: false
  # 服务配置项
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      uuc-system-group: default
  config:
    type: nacos
    # 环境迁移需根据实际情况改动，Nacos配置
    nacos:
      serverAddr: 10.128.40.208:8848
      group: SEATA_GROUP
      namespace:
  registry:
    type: nacos
    # 环境迁移需根据实际情况改动，Nacos配置
    nacos:
      application: seata-server
      server-addr: 10.128.40.208:8848
      namespace:

# mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.uuc.alarm
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*.xml

# swagger配置
swagger:
  title: 系统模块接口文档
  basePackage: com.uuc.alarm
# 环境迁移需根据实际情况改动
prometheus:
  url: http://10.128.120.26:8082/select/0/prometheus
